### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by frain45** [stedotmartin/plesk-to-s3#1]
Hello Martin,

I have tested your plesk-to-s3 tool, nice job! After one day, it seems the perfect addition to a standard Plesk install for offsite s3 backup. I had a few issues during install that might be worth reporting.

Using installation instructions. When I reach the following stage...

> python s3cmd-master/setup.py install

...my standard Centos 6.5 VPS complains that installation cannot be completed. Unfortunately I have already worked more on that server, so I cannot retrieve the error any more.
I just did...

cd /root/hypersrv.com/plesk-to-s3
python setup.py install

...and installation was successful.
Then, the following installation stage failed because files were not in the expected position:

cp {plesk-to-s3,daily,monthly}.sh /root/hypersrv.com/plesk-to-s3/

I cd'd to the directory and did...

touch plesk-to-s3.sh
vi plesk-to-s3.sh
[copy-paste file content from github]

...Repeated these steps to create daily.sh and monthly.sh.

My last issue was that I mistakenly added cron command to "psa" user, rather than root. This is stated correctly in your instructions ("add to root cron..."), but you might want to write ROOT in capitals so users will not overlook it as I did.   :-)

Last thing about instructions, you might want to state that daily.sh and monthly.sh do a server backup when started. Users should disable similar backups scheduled in Plesk to avoid overlapping.

Hope the above is of any use to you. Thanks again for the nice tool!

Alessandro

**Comment by squareborg** [comment]
Thanks @Alessandro.  Your feedback is much appreciated. I'll take a look at this later on a fresh centos 6.5 install and update the instructions.

**Comment by squareborg** [comment]
HI I have fixed the documentation. I would also note that this script does not schedule or run Plesk backups its just copies the latest backup to S3, I have cleared that up in the docs.

**Comment by frain45** [comment]
Hi Stephen, thanks for accepting my feedback.

Now plesk-to-s3 has been running for a few days and it works great. Fast 
transfer, minimum server load. I confirm that it does not run Plesk 
backups on its own, I was mistaken.

When you have time, you could add a restore script to the package. If I 
need to restore, I would run:

/opt/hypersrv.com/plesk-to-s3/restore.sh > /dev/null 2>&1

Plesk-to-s3 would do its standard job in the opposite direction 
(download the most recent backup from S3 to Plesk backup directory). 
Then I would see it in the Plesk interface.

I do not know if turning plesk-to-s3 into a Plesk extension is 
difficult, but it might be worth it. As you know offsite backup with 
Plesk is complicated, you need a dedicated backup software/service or 
rely on the buggy FTP transfer (unreliable). Your script just works, so 
it fills a gap.

Best,

Alessandro

**Comment by iamkingsleyf** [comment]
seems i will give it a try... what happens if you dont want to use a gain?
